spring.application.name=u5-w2-d3
#DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/u5-w2-d3
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver=org.postgresql.Driver
#HIBERNATE
spring.jpa.hibernate.ddl-auto=update
